CREATE TABLE travels
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    origin          VARCHAR(255)                            NOT NULL,
    destination     VARCHAR(255)                            NOT NULL,
    departure_date  DATE                                    NOT NULL,
    return_date     DATE                                    NOT NULL,
    price           NUMERIC(10, 2)                          NOT NULL,
    available_seats INTEGER                                 NOT NULL,
    description     VARCHAR(2000),
    CONSTRAINT pk_travels PRIMARY KEY (id),
    CONSTRAINT chk_travels_dates CHECK (return_date >= departure_date),
    CONSTRAINT chk_travels_available_seats CHECK (available_seats > 0)
);

CREATE INDEX idx_travel_destination ON travels (destination);
CREATE INDEX idx_travel_departure_date ON travels (departure_date);
